{{- if and .Values.volumeClaim.enabled ( not .Values.dataStorage ) }}
{{- if .Values.volumeClaim.existingClaim }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volumeClaim.existingClaim }}
  namespace: {{ .Release.Namespace }}
{{- else }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "atlantis.fullname" . }}-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "atlantis.labels" . | nindent 4 }}
  {{- with .Values.extraAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes: {{ .Values.volumeClaim.accessModes | toYaml | nindent 2 }}
  resources:
    requests:
      storage: {{ .Values.volumeClaim.dataStorage }}
  {{- if .Values.volumeClaim.storageClassName }}
  storageClassName: {{ .Values.volumeClaim.storageClassName }}
  {{- end }}
{{- end }}
{{- end }}